main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [

    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('about/<int:pk>/', views.about, name="about"),
    path('comment/<int:pk>/', views.comment, name="comment"),
    path('comment', views.comment, name="comment"),
    path('order', views.order, name="order"),
    path('teachers', views.teachers, name="teachers"),
    path('register', views.register, name="register"),
    path('login', views.CustomLoginView.as_view(), name="login"),
    path('logout', views.logout_request, name="logout"),

]

new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import export_products_csv


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('export/', export_products_csv, name='export_products_csv')

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    last_name = models.CharField(verbose_name="Прізвище", max_length=50)
    first_name = models.CharField(verbose_name="Ім'я", max_length=50)
    surname = models.CharField(verbose_name="По батькові", max_length=50)
    choose_subject = models.CharField(verbose_name="Предмет", max_length=16, null=True)
    price_per_hour = models.CharField(verbose_name="Ціна заняття за годину у грн", max_length=50)
    specialization = models.CharField(verbose_name="Напрямок викладання", max_length=50)
    experience = models.IntegerField(verbose_name="Стаж роботи(у місяцях)")
    extra_information = models.TextField(verbose_name="Додаткова інформація")
    check = models.BooleanField(default=False)
    email = models.EmailField(verbose_name="Електронна пошта", max_length=254, null=True)

    def __str__(self):
        return "{} {} {} {} {}".format(self.last_name, self.first_name, self.surname, self.price_per_hour, self.image)

    class Meta:
        verbose_name = 'Репетитор'
        verbose_name_plural = 'Репетитори'


class LeaveFeedBack(models.Model):
    feedback = models.TextField(verbose_name="Ви можете зилишити свій коментар тут", null=True)
    check = models.BooleanField(default=False, null=True)
    task = models.ForeignKey(Task, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

main/forms.py
from .models import Task, LeaveFeedBack
from django.forms import ModelForm, TextInput, Textarea, CheckboxInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["image", "first_name", "last_name", "surname", "email", "choose_subject", "price_per_hour",
                  "specialization", "experience", "extra_information",]
        widgets = {

            "last_name": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть ваше прізвище"
            }),

            "first_name": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть ваше ім'я"
            }),

            "surname": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть ваше ім'я по батькові"
            }),

            "email": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть електронну пошту для зв'язку"
            }),

            "choose_subject": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть лише один предмет, який викладатимете з перелічених вище"
            }),

            "price_per_hour": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть ціну вашого заняття за годину у гривнях"
            }),

            "specialization": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть напрямок викладання"
            }),

            "experience": TextInput(attrs={
                "class": "form-control",
                "placeholder": "Введіть стаж роботи"
            }),

            "extra_information": Textarea(attrs={
                "class": "form-control",
                "placeholder": "Введіть додаткову інформацію про себе"
            }),


        }


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class LeaveFeedBackForm(ModelForm):
    class Meta:
        model = LeaveFeedBack
        fields = ("feedback", "check", )
        widgets = {

            "feedback": Textarea(attrs={
                "class": "form-control",
                "placeholder": "Залишіть свій коментар тут"
            }),

            "check": CheckboxInput(attrs={
                "class": "form-control",
            }),

        }

main/views.py
import csv

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponse

from .models import Task, LeaveFeedBack
from .forms import TaskForm, LeaveFeedBackForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


class CustomLoginView(LoginView):
    template_name = 'main/login.html'


def index(request):
    context = {
        "title": "Головна сторінка сайту",

    }

    return render(request, "main/index.html", context)


def about(request, pk):
    tasks = Task.objects.filter(id=pk)
    feedbacks = LeaveFeedBack.objects.filter(task_id=pk)
    context = {
        "title": "Тут ви можете залишити свій коментар про викладача",
        "tasks": tasks,
        "feedbacks": feedbacks,

    }

    return render(request, "main/about.html", context)


@login_required
def comment(request, pk):
    tasks = Task.objects.filter(id=pk)
    task = Task.objects.get(id=pk)
    user = User.objects.get(id=request.user.id)
    error = ''
    if request.method == "POST":
        form = LeaveFeedBackForm(request.POST)
        if form.is_valid():
            saved_form = form.save(commit=False)
            saved_form.user = user
            saved_form.task = task
            saved_form.save()
            return redirect('main:about', pk=pk)
        else:
            error = "Форма вказана не вірно"

    form = LeaveFeedBackForm()
    context = {
        "form": form,
        "error": error,
        "title": "Тут ви можете залишити свій коментар про викладача",
        "tasks": tasks,
    }

    return render(request, "main/comment.html", context)


def order(request):
    tasks = Task.objects.order_by("id")
    min_exp = 0
    max_exp = 100000000000000
    min_price = 0
    max_price = 10000000000000
    choose_subject_filter = request.GET.get("choose_subject")
    specialization = request.GET.get("specialization")
# 0
    listings = Task.objects.all()

# 1
    if request.GET.get('price_per_hour') and request.GET.get('choose_subject') and request.GET.get('experience') \
            and request.GET.get('specialization'):

        specialization_filter = request.GET.get("specialization")
        print(specialization_filter)

        choose_subject_filter = request.GET.get("choose_subject")
        print(choose_subject_filter)

        experience_filter = request.GET.get('experience')
        print(experience_filter.split("-"))
        min_exp = int(experience_filter.split("-")[0])
        max_exp = int(experience_filter.split("-")[1].split(" ")[0])
        print(min_exp)
        print(max_exp)

        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        listings = Task.objects.filter(choose_subject__contains=choose_subject_filter,
                                       experience__range=(min_exp, max_exp),
                                       price_per_hour__range=(min_price, max_price),
                                       specialization__contains=specialization_filter)

# 2
    elif request.GET.get('price_per_hour') and request.GET.get('choose_subject') and request.GET.get('experience'):

        choose_subject_filter = request.GET.get("choose_subject")
        print(choose_subject_filter)

        experience_filter = request.GET.get('experience')
        print(experience_filter.split("-"))
        min_exp = int(experience_filter.split("-")[0])
        max_exp = int(experience_filter.split("-")[1].split(" ")[0])
        print(min_exp)
        print(max_exp)

        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        listings = Task.objects.filter(choose_subject__contains=choose_subject_filter,
                                       experience__range=(min_exp, max_exp),
                                       price_per_hour__range=(min_price, max_price), )
# 3
    elif request.GET.get('price_per_hour') and request.GET.get('choose_subject') and request.GET.get('specialization'):

        specialization_filter = request.GET.get("specialization")
        print(specialization_filter)

        choose_subject_filter = request.GET.get("choose_subject")
        print(choose_subject_filter)

        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        listings = Task.objects.filter(choose_subject__contains=choose_subject_filter,
                                       price_per_hour__range=(min_price, max_price),
                                       specialization__contains=specialization_filter)
# 4
    elif request.GET.get('choose_subject') and request.GET.get('experience') and request.GET.get('specialization'):

        specialization_filter = request.GET.get("specialization")
        print(specialization_filter)

        choose_subject_filter = request.GET.get("choose_subject")
        print(choose_subject_filter)

        experience_filter = request.GET.get('experience')
        print(experience_filter.split("-"))
        min_exp = int(experience_filter.split("-")[0])
        max_exp = int(experience_filter.split("-")[1].split(" ")[0])
        print(min_exp)
        print(max_exp)

        listings = Task.objects.filter(choose_subject__contains=choose_subject_filter,
                                       experience__range=(min_exp, max_exp),
                                       specialization__contains=specialization_filter)
# 5
    elif request.GET.get('price_per_hour') and request.GET.get('experience') and request.GET.get('specialization'):

        specialization_filter = request.GET.get("specialization")
        print(specialization_filter)

        experience_filter = request.GET.get('experience')
        print(experience_filter.split("-"))
        min_exp = int(experience_filter.split("-")[0])
        max_exp = int(experience_filter.split("-")[1].split(" ")[0])
        print(min_exp)
        print(max_exp)

        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        listings = Task.objects.filter(experience__range=(min_exp, max_exp),
                                       price_per_hour__range=(min_price, max_price),
                                       specialization__contains=specialization_filter)

# 6
    elif request.GET.get('price_per_hour') and request.GET.get('choose_subject'):
        choose_subject_filter = request.GET.get("choose_subject")
        print(choose_subject_filter)

        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        listings = Task.objects.filter(choose_subject__contains=choose_subject_filter,
                                       price_per_hour__range=(min_price, max_price), )
# 7
    elif request.GET.get('price_per_hour') and request.GET.get('experience'):
        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])
            max_price = int(prices[1])

        experience_filter = request.GET.get('experience')
        print(experience_filter.split("-"))
        min_exp = int(experience_filter.split("-")[0])
        max_exp = int(experience_filter.split("-")[1].split(" ")[0])
        print(min_exp)
        print(max_exp)

        listings = Task.objects.filter(price_per_hour__range=(min_price, max_price),
                                       experience__range=(min_exp, max_exp), )
# 8
    elif request.GET.get('price_per_hour') and request.GET.get('specialization'):
        price_per_hour_filter = request.GET.get('price_per_hour')
        print(price_per_hour_filter)

        if "+" in price_per_hour_filter:
            prices = price_per_hour_filter[:-1]
            min_price = int(prices[0])
            max_price = int(prices[0] * 10)
        else:
            prices = price_per_hour_filter.split("-")
            min_price = int(prices[0])

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
Сторінка про викладачів
{% endblock %}


{% block content %}
        <p>Тут ви можете прочитати коментарі про викладача</p>
        {% if tasks %}
                {% for el in tasks %}
                        {% if el.check == True %}
                                <div class="alert alert-warning mt-2" style="background-color:#97de6f; border: black solid">
                                    <h3>{{ el.last_name }} {{ el.first_name }} {{ el.surname }}</h3>
                                    <p>{% if el.image %}
                                        <img src="{{ el.image.url }}" alt="media">
                                    {% endif %}</p>
                                    <p>Назва предмету викладання: {{ el.choose_subject }}</p>
                                    <p>Ціна заняття за годину у грн: {{ el.price_per_hour }}</p>
                                    <p>Напрямок викладання: {{ el.specialization }}</p>
                                    <p>Стаж роботи як репетитор(у місяцях): {{ el.experience }}</p>
                                    <p>Додаткова інформація: {{ el.extra_information }}</p>
                                    <div><a href="{% url 'main:comment' pk=el.pk %}">Залишити коментар</a></div>
                                </div>
                        {% endif %}
                {% endfor %}
        {% endif %}




        {% if feedbacks %}
                {% for elem in feedbacks %}
                    {% if elem.check == True %}
                        {{ elem.user }}
                        <p>{{ elem.feedback }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}









{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
{#    {% load static %}#}

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">


</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
            <span class="fs-4">Bodia_company{% if user.is_authenticated %}, {{ user.username }}{% endif %}</span>
          </a>
          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:home' %}">Головна</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:order' %}">Замовити репетиторство</a>
            {% if user.is_authenticated %}<a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:teachers' %}">Стати репетитором</a>{% endif %}
            {% if not user.is_authenticated %}<a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:login' %}">Увійти</a>{% endif %}
            {% if not user.is_authenticated %}<a class="me-3 py-2 text-dark text-decoration-none" id="login" href="{% url 'main:register' %}">Реєстрація</a>{% endif %}
            {% if user.is_authenticated %}<a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:logout' %}">Вийти</a>{% endif %}

          </nav>
    </div>
    <div class="container" style="background-color: rgba(213,237,238,0.63); width: 10000px">

        {% block content %}{% endblock %}
    </div>






<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted" style="margin-top: 100px;">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Bodia_company
          </h6>
          <p>Наша компанія спеціалізується на онлайн заняттях. Замовники можуть отримувати приватні онлайн уроки, вони можуть проводитись як індивідуальні, так і групові заняття.</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Сторінки
          </h6>
          <p>
            <a href="{% url 'main:home' %}" class="text-reset">Головна</a>
          </p>
          <p>
            <a href="{% url 'main:order' %}" class="text-reset">Замовити репетиторство</a>
          </p>
          <p>
            <a href="{% url 'main:teachers' %}" class="text-reset">Стати репетитором</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Особистий кабінет
          </h6>
          <p>
            <a href="{% url 'main:login' %}" class="text-reset">Увійти</a>
          </p>
          <p>
            <a href="{% url 'main:register' %}" class="text-reset">Реєстрація</a>
          </p>
          <p>
            <a href="{% url 'main:logout' %}" class="text-reset">Вийти</a>
          </p>


        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Контакт</h6>
          <p><i class="fas fa-home me-3"></i> Львів, Україна</p>
          <p><i class="fas fa-envelope me-3"></i>Bodiacompany@gmail.com</p>
          <p><i class="fas fa-phone me-3"></i> + 38 111 222 33</p>
          <p><i class="fas fa-print me-3"></i> + 38 888 777 99</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Bodia_company
  </div>
  <!-- Copyright -->
</footer>





</body>
</html>

main/templates/main/comment.html
{% extends 'main/base.html' %}

{% block title %}
Сторінка про викладачів
{% endblock %}


{% block content %}
        <h1>Тут ви можете залишити свій коментар про викладача</h1>
        {% if tasks %}
                {% for el in tasks %}
                        {% if el.check == True %}
                                <div class="alert alert-warning mt-2" style="background-color:#97de6f; border: black solid">
                                    <h3>{{ el.last_name }} {{ el.first_name }} {{ el.surname }}</h3>
                                    <p>{% if el.image %}
                                        <img src="{{ el.image.url }}" alt="media">
                                    {% endif %}</p>
                                    <p>Назва предмету викладання: {{ el.choose_subject }}</p>
                                    <p>Ціна заняття за годину у грн: {{ el.price_per_hour }}</p>
                                    <p>Напрямок викладання: {{ el.specialization }}</p>
                                    <p>Стаж роботи як репетитор(у місяцях): {{ el.experience }}</p>
                                    <p>Додаткова інформація: {{ el.extra_information }}</p>
                                    <div><a href="{% url 'main:about' pk=el.pk %}">Переглянути коментарі</a></div>
                                </div>
                        {% endif %}
                {% endfor %}
        {% endif %}

    <form method="post">
                {% csrf_token %}
                <br>
                Залишіть коментар
                {{ form.feedback }}
                <br>
                <button type="submit" class="btn btn-success">Додати</button>
                <span>{{ error }}</span>
        </form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block title %}
{{ title }}
{% endblock %}


{% block content %}
{#        <h1>Головна сторінка</h1>#}
{#        <p>На цій сторінці ви можете зробити сортування по категоріям яким бажаєте</p>#}
        <div class="py-4 jumbo-pattern text-center">
            <div class="container pb-4 text-left text-black">
                <div class="h2 py-5 text-black text-center">
                    <strong>
                        Чому варто обрати Bodia_company
                    </strong>
                </div>
                <div class="row justify-content-center">
                    <div class="col-11 col-sm-12 col-md-6 offset-md-0&nbsp;col-lg-5 offset-lg-1&nbsp;pb-5">
                        <p class="h3">Потужний викладацький склад</p>
                        <p>У нашій компанії працюють найкращі викладачі України, призери олімпіадних змагань, переможці міжнародних конкурсів, висококваліфіковані студенти. Це дозволяє нам забезпечувати якісну викладацьку роботу нашої компанії.</p>
                    </div>

                    <div class="col-11 col-sm-12 col-md-6 offset-md-0&nbsp;col-lg-5 offset-lg-1&nbsp;pb-5">
                        <p class="h3">У вас є можливість стати репетитором</p>
                        <p>Якщо ви володієте хорошими викладацькими навиками та високим рівнем знань, то можете стати репетитором на нашому сайті та навчати відвідувачів сайту, для цього необхідно зареєструватись на нашому сайті та увійти в свій кабінет і заповнити форму.</p>
                    </div>

                    <div class="col-11 col-sm-12 col-md-6 offset-md-0&nbsp;col-lg-5 offset-lg-1&nbsp;pb-5">
                        <p class="h3">Можливість прочитати детальну інформацію про викладача та залишити відкгук</p>
                        <p>Всі учасники можуть детельно ознайомитись з інформацією про репеторів, яких ми вам пропонуємо, а також прочитати чи зашити їм відгук.</p>
                    </div>

                    <div class="col-11 col-sm-12 col-md-6 offset-md-0&nbsp;col-lg-5 offset-lg-1&nbsp;pb-5">
                        <p class="h3">Можливість обрати репетитора за певним критерієм</p>
                        <p>Ви можете обрати вашого репетитора, за допомогою функції сортування, по певних критеріях. Для цього на головній сторінці вам необхідно обати категорії за якими ви шукаєте викладача та натиснути кнопку пошук.</p>
                    </div>
                </div>
            </div>
        </div>


{#    <div class="filter">#}
    <form class="filter" action="{% url 'main:order' %}" method="get">
        <div class="select1">
            <label for="choose_subject">
                Сортування за назвою премета викладання
            </label>

            <select name="choose_subject">
                <option></option>
                <option>Алгебра</option>
                <option>Геометрія</option>
                <option>Англійська мова</option>
                <option>Французька мова</option>
                <option>Німецька мова</option>
                <option>Українська мова</option>
                <option>Географія</option>
                <option>Фізика</option>
                <option>Хімія</option>

            </select><br>
        </div>
    <div class="select1">
        <label for="price_per_hour">
            Сортування по ціні у грн
        </label>

        <select name="price_per_hour">
            <option></option>
            <option>0-100</option>
            <option>100-200</option>
            <option>200-300</option>
            <option>300-400</option>
            <option>400+</option>

        </select><br>
    </div>
    <div class="select1">
        <label for="specialization">
            Сортування за напрямком занять
        </label>

        <select name="specialization">
            <option></option>
            <option>ЗНО</option>
            <option>ДПА</option>
            <option>Підготовка до олімпіад</option>
            <option>Шкільні теми</option>

        </select><br>
    </div>
    <div class="select1">
    <label for="experience">
        Сортування по стажу роботи як репетитор
    </label>

        <select name="experience">
            <option></option>
            <option>0-6 місяців</option>
            <option>6-12 місяців</option>
            <option>12-24 місяців</option>
            <option>24-36 місяців</option>
            <option>36+  місяців</option>

        </select><br>
        <br>
    </div>

    <input class="search" type="submit" value="Пошук" />

    </form>



{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}

{% block title %}
    Авторизація
{% endblock %}

{% block content %}

    <form action="{% url 'main:login' %}" method="post" style="margin-top: 100px;">
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

main/templates/main/order.html
{% extends 'main/base.html' %}

{% block title %}
Замовити репетитора
{% endblock %}


{% block content %}
        <h1>Замовити репетитора</h1>
        {% if request.user.is_staff %}
            <a href="{% url 'export_products_csv' %}">Завантажити всю інформацію про викладачів</a>
        {% endif %}
        {% if listings %}
                {% for el in listings %}
                        {% if el.check == True %}
                                <div class="alert alert-warning mt-2" style="background-color:#97de6f; border: black solid">
                                    <h3>{{ el.last_name }} {{ el.first_name }} {{ el.surname }}</h3>
                                    <p>{% if el.image %}
                                        <img src="{{ el.image.url }}" alt="media">
                                    {% endif %}</p>
                                    <p>Електронна пошта для звязку: {{ el.email }}</p>
                                    <p>Назва предмету викладання: {{ el.choose_subject }}</p>
                                    <p>Ціна заняття за годину у грн: {{ el.price_per_hour }}</p>
                                    <p>Напрямок викладання: {{ el.specialization }}</p>
                                    <p>Стаж роботи як репетитор(у місяцях): {{ el.experience }}</p>
                                    <p>Додаткова інформація: {{ el.extra_information }}</p>
                                    <div><a href="{% url 'main:about' pk=el.pk %}">Переглянути коментарі</a></div>
                                    {% if user.is_authenticated %}
                                        <div>
                                            <a href="{% url 'main:comment' pk=el.pk %}">Залишити коментар</a>
                                        </div>
                                    {% endif %}
                                </div>
                        {% endif %}
                {% endfor %}
        {% endif %}
{% endblock %}